### ISSUE TITLE
Milestone 3 Progress

### ISSUE THREAD

**Issue by bedwardly-down** [bedwardly-down/BRS-PSP-Research-Initiative#8]
This will be just a simple way to show what I'm currently working and where I'm headed with this Milestone. I'm very new to doing this, so expect cruft.

- [ ] Parse and use the full bone generation algorithm in a user-applicable way
- [ ] Document the Bone Generation calculation algorithm found a couple weeks back
- [ ] Start initial conversion and extraction tool development
- [ ] Test importing and exporting model data to and from Blender
